site_name: Tabletop Simulator Community API
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo: 'img/TSIcon.png'
  favicon: 'img/Icon-Dice.png'
  custom_dir: 'theme'

extra_css:
  - css/theme.css
  - css/table.css
  - css/type_icons.css
  - css/i_icons.css
  - css/player_color_table.css

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: "\u0020"

repo_name: 'GitHub Source'
repo_url: 'https://github.com/tts-community/api'


extra:
  social:
    - type: 'reddit'
      link: 'https://www.reddit.com/r/tabletopsimulator/'
    - type: 'twitter'
      link: 'https://twitter.com/tabletopsim'
    - type: 'facebook'
      link: 'https://www.facebook.com/tabletopsimulator'
    - type: 'youtube'
      link: 'https://www.youtube.com/user/berserkgames'

nav:
  - 'Getting Started':
    - 'Introduction': index.md
    - 'Overview': overview.md
    - 'Atom': atom.md
    - 'External Editor API': externaleditorapi.md
    - 'Learning Lua': learninglua.md
    - 'System Console': systemconsole.md
    - 'Virtual Reality': vr.md
    - 'Patch Notes': 'https://www.tabletopsimulator.com/news/patch-notes'
  - 'Scripting API':
    - 'Introduction': intro.md
    - 'Types': types.md
    - 'Base': base.md
    - 'Event': event.md
    - 'Object': object.md
    - 'Object Component': component.md
    - 'AssetBundle': assetbundle.md
    - 'Book': book.md
    - 'Browser': browser.md
    - 'Built-in Object': built-in-object.md
    - 'Clock': clock.md
    - 'Color': color.md
    - 'Counter': counter.md
    - 'Custom Game Objects' : custom-game-objects.md
    - 'Grid': grid.md
    - 'JSON': json.md
    - 'Lighting': lighting.md
    - 'Music Player': musicplayer.md
    - 'Notes': notes.md
    - 'Physics': physics.md
    - 'Player': player.md
    - 'Player Color': player-color.md
    - 'RPGFigurine': rpgfigurine.md
    - 'TextTool': texttool.md
    - 'Time': time.md
    - 'Turns': turns.md
    - 'UI': ui.md
    - 'Vector': vector.md
    - 'Wait': wait.md
    - 'Web Request': webrequest.md
  - 'UI API':
    - 'Introduction': ui/introUI.md
    - 'Attributes': ui/attributes.md
    - 'Basic Elements': ui/basicelements.md
    - 'Input Elements': ui/inputelements.md
    - 'Layout/Grouping': ui/layoutgrouping.md
    - 'Defaults': ui/defaults.md
